### ISSUE TITLE
react-native-tableview

### ISSUE THREAD

**Issue by nyura123** [lelandrichardson/react-native-future#2]
I have to read the proposal in this repo more carefully, but just wanted to bring up that there's a component called react-native-tableview that allows to render native iOS TableView with cell recycling. It does that by rendering each cell as a top-level react-native app, allowing react-native JS to populate the cell, but iOS to manage the cell recycling. (See "reactModuleForCell" prop).

Maybe this idea of recyclable views as top-level react-native apps can be generalized somehow.

**Comment by lelandrichardson** [comment]
Hi @nyura123, thanks for bringing this up! I am aware of this library and actually linked to it in the proposal: https://github.com/lelandrichardson/react-native-future/blob/6c7612304114c174102981ccb27fb806175ddb93/view-recycling/README.md#current-solutions-and-reading

This library and a couple of others like it definitely have some similarities with this proposal.
